apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-cwcl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-cwcl
    app.kubernetes.io/part-of: test-annotations-app-ljcd
  name: test-annotations-cwcl
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-cwcl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-cwcl
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-nabk-tenant/test-annotations-app-ljcd/test-annotations-cwcl@sha256:1e25e7eed1483b9e421e2dd87c2ebb005c996a6ef0c52d9a40a0a2ebee13780a
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
